import pandas as pd

def prepare_input(payload):
    """This function transforms the company information into a DataFrame
        in order to display it on the front app

    Args:
        payload (InputFormulaire): user's input (or company information)

    Returns:
        pandas DataFrame: dataframe holding the user input
    """
    decoding_dict = {'A': 'Code APE',
                    'B': 'Date de création',
                    'C': 'Capital souscrit non appelé (I) (AA) 2018 (€)',
                    'D': 'TOTAL (II) (net) (BJNET) 2018 (€)',
                    'E': 'Matières premières, approvisionnements (net) (BLNET) 2018 (€)',
                    'F': 'En cours de production de biens (net) (BNNET) 2018 (€)',
                    'G': 'En cours de production de services (net) (BPNET) 2018 (€)',
                    'H': 'Produits intermédiaires et finis (net) (BRNET) 2018 (€)',
                    'I': 'Marchandises (net) (BTNET) 2018 (€)',
                    'J': 'Avances et acomptes versés sur commandes (net) (BVNET) 2018 (€)',
                    'BA': 'Clients et comptes rattachés (3) (net) (BXNET) 2018 (€)',
                    'BB': 'Autres créances (3) (net) (BZNET) 2018 (€)',
                    'BC': 'Capital souscrit et appelé, non versé (net) (CBNET) 2018 (€)',
                    'BD': 'Valeurs mobilières de placement (net) (CDNET) 2018 (€)',
                    'BE': 'Disponibilités (net) (CFNET) 2018 (€)',
                    'BF': "Charges constatées d'avance (3) (net) (CHNET) 2018 (€)",
                    'BG': 'TOTAL (III) (net) (CJNET) 2018 (€)',
                    'BH': 'Primes de remboursement des obligations (CM) 2018 (€)',
                    'BI': 'Ecarts de conversion actif (CN) 2018 (€)',
                    'BJ': 'TOTAL GENERAL(I à VI) (net) (CONET) 2018 (€)',
                    'CA': 'Capital social ou individuel (1) (DA) 2018 (€)',
                    'CB': 'Report à nouveau (DH) 2018 (€)',
                    'CC': "RESULTAT DE L'EXERCICE (bénéfice ou perte) (DI) 2018 (€)",
                    'CD': 'TOTAL (I) (DL) 2018 (€)',
                    'CE': 'TOTAL(II) (DO) 2018 (€)',
                    'CF': 'TOTAL (III) (DR) 2018 (€)',
                    'CG': 'Autres emprunts obligataires (DT) 2018 (€)',
                    'CH': 'Emprunts obligataires convertibles (DS) 2018 (€)',
                    'CI': 'Emprunts et dettes auprès des établissements de crédit (5) (DU) 2018 (€)',
                    'CJ': 'Emprunts et dettes financières divers (DV) 2018 (€)',
                    'DA': 'Avances et acomptes reçus sur commandes en cours (DW) 2018 (€)',
                    'DB': 'Dettes fournisseurs et comptes rattachés (DX) 2018 (€)',
                    'DC': 'Dettes fiscales et sociales (DY) 2018 (€)',
                    'DD': 'Dettes sur immobilisations et comptes rattachés (DZ) 2018 (€)',
                    'DE': 'Autres dettes (EA) 2018 (€)',
                    'DF': "dont comptes courants d'associés de l'exercice N (EA2) 2018 (€)",
                    'DG': "Produits constatés d'avance (EB) 2018 (€)",
                    'DH': 'TOTAL (IV) (EC) 2018 (€)',
                    'DI': 'TOTAL GENERAL (I à V) (EE) 2018 (€)',
                    'DJ': '(5)\xa0Dont concours bancaires courants, et soldes créditeurs de banques et CCP (EH) 2018 (€)',
                    'EA': "Chiffre d'affaires net (France) (FJ) 2018 (€)",
                    'EB': "Chiffre d'affaires net (Exportations et livraisons intracommunautaires) (FK) 2018 (€)",
                    'EC': "Chiffre d'affaires net (Total) (FL) 2018 (€)",
                    'ED': "Subventions d'exploitation (FO) 2018 (€)",
                    'EE': 'Reprises sur amortissements et provisions, transferts de charges (9) (FP) 2018 (€)',
                    'EF': "Total des produits d'exploitation (2) (I) (FR) 2018 (€)",
                    'EG': 'Achats de marchandises (y compris droits de douane) (FS) 2018 (€)',
                    'EH': 'Variation de stock (marchandises) (FT) 2018 (€)',
                    'EI': 'Achats de matières premières et autres approvisionnements (y compris droits de douane) (FU) 2018 (€)',
                    'EJ': 'Variation de stock (matières premières et approvisionnements) (FV) 2018 (€)',
                    'FA': 'Autres achats et charges externes (3) (6 bis) (FW) 2018 (€)',
                    'FB': 'Impôts, taxes et versements assimilés (FX) 2018 (€)',
                    'FC': 'Salaires et traitements (FY) 2018 (€)',
                    'FD': 'Charges sociales (10) (FZ) 2018 (€)',
                    'FE': "Dotations d'exploitation sur immobilisations (dotations aux amortissements) (GA) 2018 (€)",
                    'FF': "Dotations d'exploitation sur immobilisations (dotations aux provisions) (GB) 2018 (€)",
                    'FG': "Dotations d'exploitation sur actif circulant (dotations aux provisions) (GC) 2018 (€)",
                    'FH': "Dotations d'exploitation pour risques et charges (dotations aux provisions) (GD) 2018 (€)",
                    'FI': 'Autres charges (12) (GE) 2018 (€)',
                    'FJ': "Total des charges d'exploitation (4) (II) (GF) 2018 (€)",
                    'GA': "1 - RESULTAT D'EXPLOITATION (I - II) (GG) 2018 (€)",
                    'GB': 'Total des produits financiers (V) (GP) 2018 (€)',
                    'GC': 'Intérêts et charges assimilées (GR) 2018 (€)',
                    'GD': 'Total des charges financières (VI) (GU) 2018 (€)',
                    'GE': 'Dotations financières aux amortissements et provisions (GQ) 2018 (€)',
                    'GF': 'Reprises sur provisions & transferts de charges (GM) 2018 (€)',
                    'GG': 'Total des produits exceptionnels (VII) (HD) 2018 (€)',
                    'GH': 'Reprises sur provisions & transferts de charges (HC) 2018 (€)',
                    'GI': 'Dotations exceptionnelles aux amortissements et provisions (6 ter) (HG) 2018 (€)',
                    'GJ': 'Total des charges exceptionnelles (VIII) (HH) 2018 (€)',
                    'HA': '4 - RESULTAT EXCEPTIONNEL (VII - VIII) (HI) 2018 (€)',
                    'HB': '5 - BENEFICE OU PERTE (Total des produits - total des charges) (HN) 2018 (€)',
                    'HC': "Participation des salariés aux résultats de l'entreprise (HJ) 2018 (€)",
                    'HD': 'Impôts sur les bénéfices (HK) 2018 (€)',
                    'HE': 'Clients douteux ou litigieux - Montant brut (VA) 2018 (€)',
                    'HF': 'Sécurité sociale et autres organismes sociaux - Montant brut (8D) 2018 (€)',
                    'HG': 'Impôts sur les bénéfices - Montant brut (8E) 2018 (€)',
                    'HH': 'T.V.A. - Montant brut (VW) 2018 (€)',
                    'HI': 'Emprunts souscrits en cours d’exercice - à 1 an au plus (VJ2) 2018 (€)',
                    'HJ': 'Effets portés à l’escompte et non échus (YS) 2018 (€)',
                    'IA': 'Sous‐traitance (YT) 2018 (€)',
                    'IB': 'Ecarts de conversion passif (V) (ED) 2018 (€)',
                    'IC': 'Production stockée (FM) 2018 (€)',
                    'ID': 'Production immobilisée (FN) 2018 (€)',
                    'IE': '(3)\xa0Dont Crédit-bail mobilier (HP) 2018 (€)',
                    'IF': '(3)\xa0Dont Crédit-bail immobilier (HQ) 2018 (€)',
                    'IG': '3 - RESULTAT COURANT AVANT IMPOTS (I - II + III - IV + V - VI) (GW) 2018 (€)',
                    'IH': "Nombre de mois de l'exercice comptable 2018",
                    'II': 'Catégorie juridique (Niveau II)'}
    input_dict = {decoding_dict[key]:value for (key, value) in payload.items()}
    df = pd.DataFrame(input_dict, index=range(1))
    df = df.transpose()
    return df